### ISSUE TITLE
Failure on scoped package

### ISSUE THREAD

**Issue by guykisel** [ubilabs/webpack-node-modules-list#9]
This might just be because the package.json is a level deeper than expected.

```
webpack: wait until bundle finished:
10 02 2017 14:45:50.822:ERROR [karma]: { Error: ENOENT: no such file or directory, open '/Users/*/*/node_modules/@myscope/package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at /Users/*/*/node_modules/webpack-node-modules-list/index.js:38:41
    at Array.forEach (native)
    at compilation.chunks.forEach.chunk (/Users/*/*/node_modules/webpack-node-modules-list/index.js:30:10)
    at Array.forEach (native)
    at Compiler.compiler.plugin (/Users/*/*/node_modules/webpack-node-modules-list/index.js:21:24)
    at Compiler.applyPluginsAsync (/Users/*/*/node_modules/tapable/lib/Tapable.js:71:13)
    at Compiler.emitAssets (/Users/*/*/node_modules/webpack/lib/Compiler.js:226:7)
    at Watching.<anonymous> (/Users/*/*/node_modules/webpack/lib/Compiler.js:54:18)
    at /Users/*/*/node_modules/webpack/lib/Compiler.js:403:12
    at Compiler.next (/Users/*/*/node_modules/tapable/lib/Tapable.js:67:11)
    at Compiler.<anonymous> (/Users/*/*/node_modules/webpack/lib/CachePlugin.js:40:4)
    at Compiler.applyPluginsAsync (/Users/*/*/node_modules/tapable/lib/Tapable.js:71:13)
    at Compiler.<anonymous> (/Users/*/*/node_modules/webpack/lib/Compiler.js:400:9)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/*/*/node_modules/@myscope/package.json' }
```

I'll look into fixing this if I get a chance.

**Comment by yfr** [comment]
Thanks for reporting. Let me know if you need some help.

**Comment by httpete** [comment]
Hi, I am hitting this too:

Unhandled rejection Error: ENOENT: no such file or directory, open 'c:\Users\mydir\bench\myproduct\node_modules\@uirouter\package.json'

Because this directory doesn't have a package.json, any thoughts? Really need this module you have.

**Comment by givanse** [comment]
fix: https://github.com/ubilabs/webpack-node-modules-list/pull/15
